# Generated by Django 5.1.3 on 2026-01-16 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='signal_amount',
            new_name='total_amount_eur',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='purchase',
            name='signal_amount_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='signal_amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='signal_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
