# Generated by Django 5.1.3 on 2026-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_security_and_ledger_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="total_price_override",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
